version: "3"
services: 
  nginx:
    #user: 1000:1000
    image: nginx:alpine
    ports: 
      - 80:80
    volumes:
      - ./data/site:/var/www/html
      - ./data/conf.d:/etc/nginx/conf.d:ro
      - ./data/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on: 
      - php
  php:
    image: php:fpm-alpine
    volumes: 
      - ./data/site:/var/www/html
    